import React, { useState, useEffect } from 'react';
import { motion as Motion } from 'framer-motion';
import { Award, Search, Loader2, Star, Clock, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import AnimatedPage from '../components/AnimatedPage';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';
import api from '../api/api';
import './CertificateSuggestions.css';

export default function CertificateSuggestions() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [role, setRole] = useState(user?.aspiration || user?.headline || '');
  const [isGenerating, setIsGenerating] = useState(false);
  const [certificates, setCertificates] = useState([]);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const generateCertificates = async (targetRole = role) => {
    if (!targetRole.trim()) {
      toast.error('Please enter a role or field first.');
      return;
    }

    setIsGenerating(true);
    try {
      // Fetch user tokens to provide context
      let tokenStr = '';
      try {
        const tokenRes = await api.get('/auth/tokens');
        if (tokenRes.data && tokenRes.data.length > 0) {
          const titles = tokenRes.data.map(t => t.title.replace(/Completer|Communicator|Expert/g, '').trim()).join(', ');
          tokenStr = `The user has ALREADY earned career badges/tokens in these specific skills: [${titles}]. Please suggest next-level certificates that complement these existing skills. `;
        }
      } catch (err) {
        console.error('Failed to fetch tokens', err);
      }

      const prompt = `Act as an expert career advisor. The user's target domain/role is "${targetRole}". ${tokenStr}Suggest the top 6 ACTIVE professional certificates specifically for this role available on Coursera. 
      CRITICAL INSTRUCTION: You MUST ONLY suggest REAL, actually existing specific certificates. DO NOT hallucinate.
      Return ONLY a valid JSON object with exactly one key "certificates", containing an array of 6 objects. Each object must have: 
      "name" (100% verified real certificate name), 
      "provider" (Always write "Coursera"), 
      "description" (2 short sentences why it provides high value), 
      "difficulty" (Beginner/Intermediate/Advanced), 
      "duration" (e.g. "3 months"). 
      Do not return any markdown or extra text outside the JSON.`;

      const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${import.meta.env.VITE_GROQ_API_KEY}`,
            "Content-Type": "application/json"
        },
        body: JSON.stringify({
            model: "llama-3.1-8b-instant",
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" }
        })
      });

      if (!response.ok) throw new Error("Failed to fetch suggestions");
      const data = await response.json();
      const result = JSON.parse(data.choices[0].message.content);
      
      if (result.certificates && result.certificates.length > 0) {
        setCertificates(result.certificates);
        toast.success('Certificate suggestions generated!');
      } else {
        throw new Error('Invalid format received');
      }
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate suggestions. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    if (role && !hasAutoGenerated) {
      setHasAutoGenerated(true);
      generateCertificates(role);
    }
  }, [role, hasAutoGenerated]);

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  };

  return (
    <AnimatedPage className="certificates-container">
      <div className="certificates-content">
        <button className="back-btn glass-panel" onClick={() => navigate('/dashboard')} style={{ marginBottom: '2rem', display: 'flex', alignItems: 'center', gap: '8px', padding: '8px 16px', background: 'transparent', color: 'var(--text-main)', border: '1px solid var(--glass-border)', borderRadius: '8px', cursor: 'pointer' }}>
          <ArrowLeft size={18} /> Back to Dashboard
        </button>

        <div className="certificates-header">
          <Motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }}>
            <Award size={48} color="var(--primary)" style={{ marginBottom: '1rem' }} />
            <h1 className="certificates-title">
              Certificate Suggestions
            </h1>
            <p className="certificates-subtitle">
              Discover the most impactful certifications to boost your resume and stand out to recruiters for your target role.
            </p>
          </Motion.div>
        </div>

        <Motion.div 
          className="role-input-section"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <div className="role-input-group">
            <input
              type="text"
              className="role-input"
              placeholder="e.g. Data Scientist, Cloud Architect..."
              value={role}
              onChange={(e) => setRole(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && generateCertificates()}
            />
            <button 
              className="generate-btn"
              onClick={generateCertificates}
              disabled={isGenerating || !role.trim()}
            >
              {isGenerating ? <Loader2 size={20} className="loader-spinner" /> : <Search size={20} />}
              {isGenerating ? 'AI Analyzing...' : 'Suggest'}
            </button>
          </div>
        </Motion.div>

        {isGenerating && (
          <div className="loading-indicator">
            <Loader2 size={40} className="loader-spinner" />
            <p>Curating the best professional certificates globally...</p>
          </div>
        )}

        {!isGenerating && certificates.length > 0 && (
          <Motion.div 
            className="certificates-grid"
            variants={containerVariants}
            initial="hidden"
            animate="show"
          >
            {certificates.map((cert, index) => (
              <Motion.div key={index} variants={itemVariants} className="certificate-card glass-panel">
                <div className="cert-icon-wrapper">
                  <Award size={24} color="var(--primary)" />
                </div>
                <h3 className="cert-name">{cert.name}</h3>
                <div className="cert-provider">Issued by {cert.provider}</div>
                <p className="cert-desc">{cert.description}</p>
                
                <div className="cert-meta">
                  <div className="cert-diff">
                    <Star size={14} color="#f59e0b" />
                    {cert.difficulty}
                  </div>
                  <div className="cert-time">
                    <Clock size={14} color="#9ca3af" />
                    {cert.duration}
                  </div>
                </div>
                
                <a 
                  href={`https://www.coursera.org/search?query=${encodeURIComponent(cert.name)}`} 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="view-course-btn outline-btn"
                  style={{ marginTop: '1rem', display: 'block', textAlign: 'center', textDecoration: 'none' }}
                >
                  Enroll on Platform 🎓
                </a>
              </Motion.div>
            ))}
          </Motion.div>
        )}
      </div>
    </AnimatedPage>
  );
}